// TOKENS //
import { primitive } from "./primitive";

export const semantic = {
  fontFamily: {
    title: {
      thin: primitive["fontFamily"]["primary"]["thin"],
      extraLight: primitive["fontFamily"]["primary"]["extraLight"],
      light: primitive["fontFamily"]["primary"]["light"],
      regular: primitive["fontFamily"]["primary"]["regular"],
      medium: primitive["fontFamily"]["primary"]["medium"],
      semiBold: primitive["fontFamily"]["primary"]["semiBold"],
      bold: primitive["fontFamily"]["primary"]["bold"],
      extraBold: primitive["fontFamily"]["primary"]["extraBold"],
      black: primitive["fontFamily"]["primary"]["black"],
    },
    body: {
      thin: primitive["fontFamily"]["secondary"]["thin"],
      extraLight: primitive["fontFamily"]["secondary"]["extraLight"],
      light: primitive["fontFamily"]["secondary"]["light"],
      regular: primitive["fontFamily"]["secondary"]["regular"],
      medium: primitive["fontFamily"]["secondary"]["medium"],
      semiBold: primitive["fontFamily"]["secondary"]["semiBold"],
      bold: primitive["fontFamily"]["secondary"]["bold"],
      extraBold: primitive["fontFamily"]["secondary"]["extraBold"],
      black: primitive["fontFamily"]["secondary"]["black"],
    },
  },
  padding: {
    xsmall: primitive["spacing"]["2"],
    small: primitive["spacing"]["4"],
    regular: primitive["spacing"]["8"],
    medium: primitive["spacing"]["12"],
    large: primitive["spacing"]["16"],
    xlarge: primitive["spacing"]["20"],
    xxlarge: primitive["spacing"]["24"],
  },
  gap: {
    xsmall: primitive["spacing"]["2"],
    small: primitive["spacing"]["4"],
    regular: primitive["spacing"]["8"],
    medium: primitive["spacing"]["12"],
    large: primitive["spacing"]["16"],
    xlarge: primitive["spacing"]["20"],
    xxlarge: primitive["spacing"]["24"],
  },
  margin: {
    xsmall: primitive["spacing"]["2"],
    small: primitive["spacing"]["4"],
    regular: primitive["spacing"]["8"],
    medium: primitive["spacing"]["12"],
    large: primitive["spacing"]["16"],
    xlarge: primitive["spacing"]["20"],
    xxlarge: primitive["spacing"]["24"],
  },
  borderRadius: {
    small: primitive["borderRadius"]["sm"],
    medium: primitive["borderRadius"]["md"],
    large: primitive["borderRadius"]["lg"],
  },
  fontWeight: {
    heading1: primitive["fontWeight"]["700"],
    heading2: primitive["fontWeight"]["700"],
    heading3: primitive["fontWeight"]["700"],
    heading4: primitive["fontWeight"]["700"],
    large: primitive["fontWeight"]["500"],
    small: primitive["fontWeight"]["400"],
    paragraph: primitive["fontWeight"]["400"],
    link: primitive["fontWeight"]["500"],
    caption: primitive["fontWeight"]["400"],
    error: primitive["fontWeight"]["400"],
    thin: primitive["fontWeight"]["100"],
    extraLight: primitive["fontWeight"]["200"],
    light: primitive["fontWeight"]["300"],
    regular: primitive["fontWeight"]["400"],
    medium: primitive["fontWeight"]["500"],
    semiBold: primitive["fontWeight"]["600"],
    bold: primitive["fontWeight"]["700"],
    extraBold: primitive["fontWeight"]["800"],
    black: primitive["fontWeight"]["900"],
  },
  fontSize: {
    heading1: primitive["fontSize"]["4xl"],
    heading2: primitive["fontSize"]["3xl"],
    heading3: primitive["fontSize"]["2xl"],
    heading4: primitive["fontSize"]["xl"],
    paragraph: primitive["fontSize"]["rg"],
    link: primitive["fontSize"]["rg"],
    error: primitive["fontSize"]["xs"],
    "2xsmall": primitive["fontSize"]["2xs"],
    xsmall: primitive["fontSize"]["xs"],
    small: primitive["fontSize"]["sm"],
    caption: primitive["fontSize"]["xs"],
    regular: primitive["fontSize"]["rg"],
    medium: primitive["fontSize"]["md"],
    large: primitive["fontSize"]["lg"],
    xlarge: primitive["fontSize"]["xl"],
    "2xlarge": primitive["fontSize"]["2xl"],
    "3xlarge": primitive["fontSize"]["3xl"],
    "4xlarge": primitive["fontSize"]["4xl"],
    "5xlarge": primitive["fontSize"]["5xl"],
    "6xlarge": primitive["fontSize"]["6xl"],
    "7xlarge": primitive["fontSize"]["7xl"],
    "8xlarge": primitive["fontSize"]["8xl"],
    "9xlarge": primitive["fontSize"]["9xl"],
    "10xlarge": primitive["fontSize"]["10xl"],
  },
  color: {
    foreground: {
      light: {
        tint: primitive["color"]["black"]["500"],
        bright: primitive["color"]["black"]["500"],
        regular: primitive["color"]["black"]["500"],
        shade: primitive["color"]["black"]["500"],
        deep: primitive["color"]["black"]["500"],
      },
      dark: {
        tint: primitive["color"]["white"]["100"],
        bright: primitive["color"]["white"]["100"],
        regular: primitive["color"]["white"]["100"],
        shade: primitive["color"]["white"]["100"],
        deep: primitive["color"]["white"]["100"],
      },
    },
    brand: {
      primary: {
        tint: primitive["color"]["purple"]["100"],
        bright: primitive["color"]["purple"]["300"],
        regular: primitive["color"]["purple"]["500"],
        shade: primitive["color"]["purple"]["700"],
        deep: primitive["color"]["purple"]["900"],
        contrast: primitive["color"]["white"]["100"],
        rgb: primitive["color"]["purple"]["500Rgb"],
      },
      secondary: {
        tint: primitive["color"]["yellow"]["100"],
        bright: primitive["color"]["yellow"]["300"],
        regular: primitive["color"]["yellow"]["500"],
        shade: primitive["color"]["yellow"]["700"],
        deep: primitive["color"]["yellow"]["900"],
        contrast: primitive["color"]["white"]["100"],
        rgb: primitive["color"]["yellow"]["500Rgb"],
      },
      tertiary: {
        tint: primitive["color"]["blue"]["100"],
        bright: primitive["color"]["blue"]["300"],
        regular: primitive["color"]["blue"]["500"],
        shade: primitive["color"]["blue"]["700"],
        deep: primitive["color"]["blue"]["900"],
        contrast: primitive["color"]["white"]["100"],
        rgb: primitive["color"]["blue"]["500Rgb"],
      },
      neutralDark: {
        "100": primitive["color"]["grey"]["500"],
        "200": primitive["color"]["grey"]["600"],
        "300": primitive["color"]["grey"]["700"],
        "400": primitive["color"]["grey"]["800"],
        "500": primitive["color"]["black"]["100"],
        "600": primitive["color"]["black"]["300"],
        "700": primitive["color"]["black"]["500"],
        "800": primitive["color"]["black"]["700"],
        "900": primitive["color"]["black"]["900"],
      },
      neutralLight: {
        "100": primitive["color"]["white"]["100"],
        "200": primitive["color"]["white"]["200"],
        "300": primitive["color"]["white"]["300"],
        "400": primitive["color"]["white"]["500"],
        "500": primitive["color"]["white"]["700"],
        "600": primitive["color"]["grey"]["100"],
        "700": primitive["color"]["grey"]["200"],
        "800": primitive["color"]["grey"]["300"],
        "900": primitive["color"]["grey"]["400"],
      },
    },
    success: {
      tint: primitive["color"]["green"]["100"],
      regular: primitive["color"]["green"]["500"],
      deep: primitive["color"]["green"]["700"],
      contrast: primitive["color"]["white"]["100"],
    },
    error: {
      tint: primitive["color"]["red"]["100"],
      regular: primitive["color"]["red"]["500"],
      deep: primitive["color"]["red"]["700"],
      contrast: primitive["color"]["white"]["100"],
    },
    warning: {
      tint: primitive["color"]["orange"]["100"],
      regular: primitive["color"]["orange"]["500"],
      deep: primitive["color"]["orange"]["700"],
      contrast: primitive["color"]["white"]["100"],
    },
    info: {
      tint: primitive["color"]["teal"]["100"],
      regular: primitive["color"]["teal"]["500"],
      deep: primitive["color"]["teal"]["700"],
      contrast: primitive["color"]["white"]["100"],
    },
    text: {
      tint: primitive["color"]["black"]["100"],
      bright: primitive["color"]["black"]["300"],
      regular: primitive["color"]["black"]["500"],
      shade: primitive["color"]["black"]["700"],
      deep: primitive["color"]["black"]["900"],
    },
    link: {
      default: primitive["color"]["blue"]["500"],
      hovered: primitive["color"]["blue"]["400"],
      pressed: primitive["color"]["blue"]["400"],
      visited: primitive["color"]["purple"]["500"],
    },
    skeleton: {
      default: primitive["color"]["white"]["300"],
      subtle: primitive["color"]["white"]["500"],
    },
    background: {
      light: {
        tint: primitive["color"]["white"]["100"],
        bright: primitive["color"]["white"]["200"],
        regular: primitive["color"]["white"]["300"],
        shade: primitive["color"]["white"]["400"],
        deep: primitive["color"]["white"]["500"],
      },
      dark: {
        tint: primitive["color"]["black"]["100"],
        bright: primitive["color"]["black"]["300"],
        regular: primitive["color"]["black"]["500"],
        shade: primitive["color"]["black"]["700"],
        deep: primitive["color"]["black"]["900"],
      },
    },
  },
  lineHeight: {
    heading1: primitive["lineHeight"]["medium"],
    heading2: primitive["lineHeight"]["medium"],
    heading3: primitive["lineHeight"]["medium"],
    heading4: primitive["lineHeight"]["regular"],
    large: primitive["lineHeight"]["large"],
    small: primitive["lineHeight"]["small"],
    paragraph: primitive["lineHeight"]["medium"],
    link: primitive["lineHeight"]["medium"],
    caption: primitive["lineHeight"]["medium"],
  },
};
